### ISSUE TITLE
IBD: Wallet Sync issue 

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisCore#214]
I loaded Stratis Core 1.1.0 on a new Win10 miniPC for the very first time. Here is the spec:
Atom x5-Z8350
4GB ram
64GB HD
IBD started around 10PM (PST). I left it running overnight. Woke up this morning and saw the height was only 120,000 or so with 0 connections. I close the app and relaunch. After about 1 minute, more connections and the height started to increase; this was about 7:30 AM (PST). I came home from work and the sync stopped again; this time I was at 134,000 or so with 2 connections. I close the app and relaunch. Nothing seem to update; I check Task Manager and Stratis.StratisD was not running. I close the app and relaunch again. After about 1 minute, more connections and the height started to increase. I turn off sleep. Now it is at 401154 with 16 connections. 

My thoughts on the issue are:
- wifi
- sleep (default to 10 min)

It seems somehow the process isn't able to recovered from whatever happened. I can give you the full logs if needed. @dev0tion Only error in log :

[2019-03-15 01:50:55.1071 1] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.LogAndAddException An error occurred: 'DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: C:\Users\Stratis\AppData\Roaming\StratisNode\stratis\StratisMain\chain\_DBreezeSchema ---> System.IO.IOException: The process cannot access the file 'C:\Users\Stratis\AppData\Roaming\StratisNode\stratis\StratisMain\chain\_DBreezeSchema' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at DBreeze.Storage.FSR.InitFiles()
   --- End of inner exception stack trace ---
   at DBreeze.Storage.FSR.InitFiles()
   at DBreeze.Storage.StorageLayer..ctor(String fileName, TrieSettings trieSettings, DBreezeConfiguration configuration)
   at DBreeze.Scheme.OpenSchema()
   at DBreeze.DBreezeEngine.InitDb()
   --- End of inner exception stack trace ---
   at DBreeze.DBreezeEngine.InitDb()
   at Stratis.Bitcoin.Base.ChainRepository..ctor(String folder, ILoggerFactory loggerFactory, DBreezeSerializer dBreezeSerializer) in C:\Users\StratisTest\Desktop\DevOps\Agent2\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\ChainRepository.cs:line 46
   at Stratis.Bitcoin.Base.ChainRepository..ctor(DataFolder dataFolder, ILoggerFactory loggerFactory, DBreezeSerializer dBreezeSerializer) in C:\Users\StratisTest\Desktop\DevOps\Agent2\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\ChainRepository.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Stratis.Bitcoin.Builder.FullNodeServiceProvider.get_Features()+MoveNext() in C:\Users\StratisTest\Desktop\DevOps\Agent2\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeServiceProvider.cs:line 53
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\StratisTest\Desktop\DevOps\Agent2\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 117'

**Comment by dev0tion** [comment]
Thanks for the report @trunghieud, I'll look into it.

The DBreeze exception is probably caused by the fact that there was still an instance of the Stratis.StratisD running when restarting at some point, so the new instance could not access the data folder. This exception is unrelated to your node stalling in sleepmode.

We'll keep you posted!

**Comment by trunghieud** [comment]
Btw, it would be nice improvement to have the logs show in the user’s time zone and not London :)
