### ISSUE TITLE
Closing Core wallet shows error in log with Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.LogAndAddException

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisCore#266]
When I close the wallet, I see this error in the logs:

[2019-08-26 16:18:02.6352 30] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.LogAndAddException An error occurred: 'System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Stratis Core\mempool.dat.new' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Stratis.Bitcoin.Features.MemoryPool.MempoolPersistence.Save(Network network, IEnumerable`1 toSave, String fileName) in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolPersistence.cs:line 219
   at Stratis.Bitcoin.Features.MemoryPool.MempoolPersistence.Save(Network network, ITxMempool memPool, String fileName) in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolPersistence.cs:line 191
   at Stratis.Bitcoin.Features.MemoryPool.MempoolManager.SavePool() in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolManager.cs:line 150
   at Stratis.Bitcoin.Features.MemoryPool.MempoolFeature.Dispose() in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.MemoryPool\MempoolFeature.cs:line 118
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Dispose>b__4_0(IFullNodeFeature feature) in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 76
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\StratisTest\Desktop\DevOps\Agent1\_work\3\s\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 111'

**Comment by dev0tion** [comment]
This is most likely a SBFN problem.
Pinging @fassadlr @zeptin @maciejzaleski

**Comment by fassadlr** [comment]
@trunghieud Can you confirm whether this happens every time that you shut the wallet down? Are there any instances of StratisD.exe perhaps still running?

Close all of them and then start the wallet and close, is the error still there?

As a last resort just delete that file.

**Comment by trunghieud** [comment]
@fassadlr I don’t believe this always happen when shutting down the wallet. The file you want to delete is “mempool.dat.new”? I can monitor once I get my wallet up and running. Right now I can’t start it due to an error. I reported the issue in another ticket.

**Comment by fassadlr** [comment]
Yes just delete the mempool file and start the wallet.

**Comment by trunghieud** [comment]
Got it. My wallet is working now after peers.json was corrupted. I will
monitor this issue.
