### ISSUE TITLE
cannot expand pattern error when compiling for windows

### ISSUE THREAD

**Issue by einewton** [stratisproject/StratisCore#69]
I am getting an error when trying to compile for windows:
**Command:** npm run package:windows

**Error**: cannot expand pattern "${productName}-v${version}-setup-${os}-${env.arch}.${ext}": env arch is not defined

**npm debug log**:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package:windows' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prepackage:windows',
4 verbose run-script   'package:windows',
4 verbose run-script   'postpackage:windows' ]
5 info lifecycle stratis-core@0.2.0~prepackage:windows: stratis-core@0.2.0
6 silly lifecycle stratis-core@0.2.0~prepackage:windows: no script for prepackage:windows, continuing
7 info lifecycle stratis-core@0.2.0~package:windows: stratis-core@0.2.0
8 verbose lifecycle stratis-core@0.2.0~package:windows: unsafe-perm in lifecycle true
9 verbose lifecycle stratis-core@0.2.0~package:windows: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\42\Desktop\FullNodeUI-master\FullNode.UI\node_modules\.bin;C:\Users\42\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\42\AppData\Local\Programs\Python\Python36-32\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\42\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\42\AppData\Local\Programs\Python\Python36-32\;C:\Users\42\.dnx\bin;C:\Program Files\SDCC\bin;C:\Users\42\AppData\Local\Microsoft\WindowsApps;C:\Users\42\AppData\Roaming\npm;C:\Users\42\AppData\Local\Programs\Fiddler;C:\Users\42\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle stratis-core@0.2.0~package:windows: CWD: C:\Users\42\Desktop\FullNodeUI-master\FullNode.UI
11 silly lifecycle stratis-core@0.2.0~package:windows: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build:prod && npx electron-builder build --windows' ]
12 silly lifecycle stratis-core@0.2.0~package:windows: Returned: code: 1  signal: null
13 info lifecycle stratis-core@0.2.0~package:windows: Failed to exec package:windows script
14 verbose stack Error: stratis-core@0.2.0 package:windows: `npm run build:prod && npx electron-builder build --windows`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid stratis-core@0.2.0
16 verbose cwd C:\Users\42\Desktop\FullNodeUI-master\FullNode.UI
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package:windows"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error stratis-core@0.2.0 package:windows: `npm run build:prod && npx electron-builder build --windows`
22 error Exit status 1
23 error Failed at the stratis-core@0.2.0 package:windows script 'npm run build:prod && npx electron-builder build --windows'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the stratis-core package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:prod && npx electron-builder build --windows
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs stratis-core
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls stratis-core
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by bokobza** [comment]
Thanks for reporting that.
The problem is that env.arch is only recognized by Appveyor, which is the service we use to build our Windows packages.
And we need this to be configurable in order to produce 32 and 64-bit compatible packages.
I think we actually need to review these https://github.com/stratisproject/FullNodeUI#build-the-ui-for-production steps, they're a bit too simplistic. A script that does the job locally will be more appropriate.
I'm on it, thanks @einewton .

**Comment by bokobza** [comment]
The scripts to package the wallets locally can be found under https://github.com/stratisproject/StratisCore/tree/master/Scripts
